### ISSUE TITLE
Add TAG's stuff

### ISSUE THREAD

**Issue by SudoJanast** [discord-bugcenter/BC_HelperBot#106]
Integrate a TAG system when opening tickets

[opened] Help me
[closed] Testing
[solved] 1+1?
[duplicate] Help me

**Comment by AiroPi** [comment]
This could be a good idea, but I thing it will be unnecessary to do since forum channels will come soon. I don't want to add new things to the help system because all this work will be "cancelled" when forums will arrive. 

It is still an interesting idea, but unfortunately I will not work on this.
